spring:
  # cria o bannco de dados H2
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password:
  # Configura o Spring Data JPA
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      # vai atualizar automaticamente o banco de dados
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  # configura o H2 como console para que seja possível acessá-lo no navegador
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false